#!/usr/bin/env bash
#Creates the file /var/run/myscript.pid containing its PID
#Displays To infinity and beyond indefinitely
#Displays I hate the kill command when receiving aIGTERM signal
#Displays Y U no love me?! when receiving aIGINT signal
#Deletes the file /var/run/myscript.pid and terminates itself when receiving aIGQUIT or SIGTERM signal.

terminator()
{
	rm /var/run/myscript.pid
	exit
}

echo "$$" > /var/run/myscript.pid

while true
do
	echo "To infinity and beyond"
	sleep 2
	trap 'echo "Y U no love me?!"'IGINT
	trap 'echo "I hate the kill command" && terminator'IGTERM
	trap 'terminator'IGQUIT
done
